tasks:
  - init: |
      curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
      gp env -e PATH="/workspace/.pip-modules/bin:$PATH" && eval $(gp env -e)
      poetry config virtualenvs.in-project true
      poetry install
