tasks:
  - init: Install poetry
    command: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
  - init: Configure poetry
    command: poetry config virtualenvs.in-project true
  - init: Install dependencies
    command: poetry install
